name: Update CSV Daily

on:
  schedule:
    - cron: "0 18 * * *"  # Run daily at 18:00 UTC (adjust if needed)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python scripts/update_csv.py  # Updated path to the script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
